# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minesweeper.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drawArea = QtWidgets.QGraphicsView(self.centralwidget)
        self.drawArea.setObjectName("drawArea")
        self.verticalLayout.addWidget(self.drawArea)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imgBttn = QtWidgets.QPushButton(self.widget_3)
        self.imgBttn.setMinimumSize(QtCore.QSize(65, 65))
        self.imgBttn.setMaximumSize(QtCore.QSize(65, 65))
        self.imgBttn.setBaseSize(QtCore.QSize(60, 0))
        self.imgBttn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/bttn"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imgBttn.setIcon(icon)
        self.imgBttn.setIconSize(QtCore.QSize(60, 60))
        self.imgBttn.setObjectName("imgBttn")
        self.horizontalLayout_2.addWidget(self.imgBttn)
        self.gridLayout.addWidget(self.widget_3, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_2)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 20))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuStatistics = QtWidgets.QMenu(self.menubar)
        self.menuStatistics.setObjectName("menuStatistics")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionColor = QtWidgets.QAction(MainWindow)
        self.actionColor.setObjectName("actionColor")
        self.actionSize = QtWidgets.QAction(MainWindow)
        self.actionSize.setObjectName("actionSize")
        self.actionGameplay = QtWidgets.QAction(MainWindow)
        self.actionGameplay.setObjectName("actionGameplay")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionInterval = QtWidgets.QAction(MainWindow)
        self.actionInterval.setObjectName("actionInterval")
        self.actionOverall = QtWidgets.QAction(MainWindow)
        self.actionOverall.setObjectName("actionOverall")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuSettings.addAction(self.actionColor)
        self.menuSettings.addAction(self.actionSize)
        self.menuSettings.addAction(self.actionGameplay)
        self.menuSettings.addAction(self.actionSave)
        self.menuSettings.addAction(self.actionOpen)
        self.menuStatistics.addAction(self.actionClear)
        self.menuStatistics.addAction(self.actionInterval)
        self.menuStatistics.addAction(self.actionOverall)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuStatistics.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Restart..."))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuStatistics.setTitle(_translate("MainWindow", "Statistics"))
        self.actionColor.setText(_translate("MainWindow", "Color"))
        self.actionSize.setText(_translate("MainWindow", "Size"))
        self.actionGameplay.setText(_translate("MainWindow", "Gameplay"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionInterval.setText(_translate("MainWindow", "Interval"))
        self.actionOverall.setText(_translate("MainWindow", "Overall"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

import resources_rc
